# Generated by Django 4.2 on 2023-04-16 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(default=datetime.datetime(2023, 4, 16, 17, 41, 5, 922146, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
