# Generated by Django 4.0.4 on 2023-04-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_device_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='checked_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
