# Generated by Django 4.0.4 on 2023-04-16 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_devicelog_checked_out_date_devicelog_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='checkout_condition',
            field=models.TextField(default=datetime.datetime(2023, 4, 16, 19, 12, 51, 225394, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelog',
            name='returned_condition',
            field=models.TextField(default=datetime.datetime(2023, 4, 16, 19, 12, 59, 260648, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
