# Generated by Django 4.0.4 on 2023-04-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_devicelog_checkout_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='condition',
            new_name='latest_condition',
        ),
        migrations.AddField(
            model_name='device',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
